### ISSUE TITLE
tinycuda的问题， Unknown compute capability.

### ISSUE THREAD

**Issue by justdi123** [IGLICT/SketchDream#9]
你好，我觉得这个项目很好，但在Ubuntu上运行时遇到一些问题。一开始tinycuda这个包一直安装不上，查了一些资料编译安装成功了，但是运行示例`./scripts/golden_fish.sh`时出现了一些问题，

```
/content/SketchDream
Traceback (most recent call last):
  File "/content/SketchDream/launch.py", line 238, in <module>
    main(args, extras)
  File "/content/SketchDream/launch.py", line 74, in main
    import threestudio
  File "/content/SketchDream/threestudio/__init__.py", line 36, in <module>
    from . import data, models, systems
  File "/content/SketchDream/threestudio/data/__init__.py", line 1, in <module>
    from . import ( 
  File "/content/SketchDream/threestudio/data/co3d.py", line 17, in <module>
    from threestudio.data.uncond import (
  File "/content/SketchDream/threestudio/data/uncond.py", line 13, in <module>
    from threestudio.utils.base import Updateable
  File "/content/SketchDream/threestudio/utils/__init__.py", line 1, in <module>
    from . import base
  File "/content/SketchDream/threestudio/utils/base.py", line 7, in <module>
    from threestudio.utils.misc import get_device, load_module_weights
  File "/content/SketchDream/threestudio/utils/misc.py", line 5, in <module>
    import tinycudann as tcnn
  File "/usr/local/lib/python3.10/dist-packages/tinycudann-1.7-py3.10-linux-x86_64.egg/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/usr/local/lib/python3.10/dist-packages/tinycudann-1.7-py3.10-linux-x86_64.egg/tinycudann/modules.py", line 19, in <module>
    raise EnvironmentError("Unknown compute capability. Ensure PyTorch with CUDA support is installed.")
OSError: Unknown compute capability. Ensure PyTorch with CUDA support is installed.
``` 
使用的是`!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`
，因为发现用colab自带的版本可以编译成功，用`torch1.12.1+cu113`有时候可以编译成功但也会出现相同的问题，环境变量也尝试调了，确定`torch.cuda.is_available()`为`True`且`import tinycudann as tcnn`也不会报错，不太感觉是tinycuda的问题了，但现在没有太多头绪了，如果能帮忙找出问题的话感激不尽！

**Comment by yuzewang1998** [comment]
您好，我遇到了同样的问题，请问您是否解决了呢？我在threestudio可以正常运行torch.cuda.is_available();import tinycudann 也正常。

**Comment by justdi123** [comment]
> 您好，我遇到了同样的问题，请问您是否解决了呢？我在threestudio可以正常运行torch.cuda.is_available();import tinycudann 也正常。

我已经解决了，请修改golden_fish.sh里面的GPU参数为0，再colab上只有一个GPU，我是这么就好了

**Comment by justdi123** [comment]
> 您好，我遇到了同样的问题，请问您是否解决了呢？我在threestudio可以正常运行torch.cuda.is_available();import tinycudann 也正常。

我已经解决了，请修改golden_fish.sh里面的GPU参数为0，在colab上只有一个GPU，我是这么就好了

**Comment by yuzewang1998** [comment]
> > 您好，我遇到了同样的问题，请问您是否解决了呢？我在threestudio可以正常运行torch.cuda.is_available();import tinycudann 也正常。
> 
> 我已经解决了，请修改golden_fish.sh里面的GPU参数为0，在colab上只有一个GPU，我是这么就好了

感谢您的回复，已解决！
